# Generated by Django 3.1 on 2022-04-13 18:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('garpix_page', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='название')),
                ('model_hostel', models.CharField(max_length=150, verbose_name='модель')),
                ('price_min', models.IntegerField(verbose_name='цена минимальная')),
                ('price_max', models.IntegerField(verbose_name='цена максимальная')),
                ('rating', models.IntegerField(verbose_name='рейтинг')),
                ('image', models.ImageField(upload_to='hotel', verbose_name='фото')),
            ],
            options={
                'verbose_name': 'Отель',
                'verbose_name_plural': 'Отели',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='HotelListPage',
            fields=[
                ('basepage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='garpix_page.basepage')),
            ],
            options={
                'verbose_name': 'HotelList',
                'verbose_name_plural': 'HotelLists',
                'ordering': ('-created_at',),
            },
            bases=('garpix_page.basepage',),
        ),
    ]
