# Generated by Django 3.1 on 2022-04-13 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0004_auto_20220413_2208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='stars',
            field=models.IntegerField(default=1, verbose_name='количество звезд'),
        ),
    ]
