# Generated by Django 3.1 on 2022-04-22 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0005_auto_20220413_2209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='price_max',
            field=models.IntegerField(blank=True, verbose_name='цена максимальная'),
        ),
    ]
