# Generated by Django 3.1 on 2022-04-22 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0006_auto_20220422_1015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='model_hostel',
            field=models.CharField(choices=[('МОТЕЛЬ', 'МОТЕЛЬ'), ('ГОСТИНИЦА', 'ГОСТИНИЦА'), ('АПАРТАМЕНТЫ', 'АПАРТАМЕНТЫ')], max_length=150, verbose_name='модель'),
        ),
    ]
