# Generated by Django 3.1 on 2022-04-10 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cause',
            name='description',
        ),
        migrations.AlterField(
            model_name='cause',
            name='name',
            field=models.CharField(max_length=150, verbose_name='причина'),
        ),
    ]
