# Generated by Django 3.1 on 2022-04-10 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20220410_1055'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cause',
            options={'ordering': ('id',), 'verbose_name': 'Причина', 'verbose_name_plural': 'Причины'},
        ),
    ]
