# Generated by Django 3.1 on 2022-04-10 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20220410_1138'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recommendation',
            name='home_page',
        ),
    ]
