# Generated by Django 3.1 on 2022-04-11 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_remove_recommendation_home_page'),
    ]

    operations = [
        migrations.CreateModel(
            name='Additionally',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='причина')),
                ('description', models.CharField(max_length=150, verbose_name='рекомендация')),
            ],
            options={
                'verbose_name': 'Причина дополнительно',
                'verbose_name_plural': 'Причины дополнительно',
                'ordering': ('id',),
            },
        ),
    ]
