# Generated by Django 3.1 on 2022-04-12 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_auto_20220412_2137'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tagline',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tagline', models.CharField(max_length=150, verbose_name='слоган')),
            ],
            options={
                'verbose_name': 'Слоган',
                'verbose_name_plural': 'Слоганы',
                'ordering': ('id',),
            },
        ),
    ]
