# Generated by Django 3.1 on 2022-04-12 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_tagline'),
    ]

    operations = [
        migrations.CreateModel(
            name='Footer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hashtag', models.CharField(default='#VISITSEDONA', max_length=20, verbose_name='хештег')),
                ('phone', models.CharField(max_length=20, verbose_name='телефон')),
                ('twitter', models.CharField(max_length=60, verbose_name='twitter')),
                ('facebook', models.CharField(max_length=60, verbose_name='facebook')),
                ('youtube', models.CharField(max_length=60, verbose_name='youtube')),
            ],
            options={
                'verbose_name': 'Подвал',
                'verbose_name_plural': 'Подвал',
                'ordering': ('id',),
            },
        ),
    ]
