# Generated by Django 3.1 on 2022-04-13 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_footer'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='logo',
            options={'verbose_name': 'Лого', 'verbose_name_plural': 'Лого'},
        ),
        migrations.AlterField(
            model_name='footer',
            name='facebook',
            field=models.CharField(blank=True, max_length=60, verbose_name='facebook'),
        ),
        migrations.AlterField(
            model_name='footer',
            name='phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='телефон'),
        ),
        migrations.AlterField(
            model_name='footer',
            name='twitter',
            field=models.CharField(blank=True, max_length=60, verbose_name='twitter'),
        ),
        migrations.AlterField(
            model_name='footer',
            name='youtube',
            field=models.CharField(blank=True, max_length=60, verbose_name='youtube'),
        ),
    ]
