# Generated by Django 3.1 on 2022-04-17 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_auto_20220413_2126'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='бронировние', max_length=50, verbose_name='бронировние')),
                ('arrival_date', models.DateField(verbose_name='дата заезда')),
                ('date_of_departure', models.DateField(verbose_name='дата выезда')),
                ('adults', models.IntegerField(verbose_name='взрослые')),
                ('children', models.IntegerField(verbose_name='дети')),
            ],
            options={
                'verbose_name': 'Бронировние',
                'verbose_name_plural': 'Бронировния',
                'ordering': ('id',),
            },
        ),
    ]
