# Generated by Django 3.1 on 2022-04-17 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0023_auto_20220417_1302'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='children',
            new_name='kids',
        ),
    ]
